spring:
  datasource:
    url: jdbc:mysql://localhost/privacy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sj2000617!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 8.130.79.250
    port: 6379
    database: 0
    password: Sj2000617!
  #  swagger配置
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

server:
  port: 444
  ssl:
    key-store: classpath:jason21.top.jks
    key-store-password: 6dncpu83
    key-store-type: JKS

upload:
  location: /Users/parsifal/Downloads/PrivacyProtection/upload/ # 文件存储路径
  avatarLocation: /Users/parsifal/Downloads/PrivacyProtection/avatar/ # 头像存储路径
  chaincodeLocation: /Users/parsifal/Downloads/PrivacyProtection/chaincode/src/ # 链码存储路径
  url: https://localhost:444/upload/ # 文件访问前缀
  avatarUrl: https://localhost:444/avatar/ # 头像访问前缀
  chaincodeUrl: https://localhost:444/chaincode/ # 链码访问前缀

