spring:
  datasource:
    url: jdbc:mysql://82.156.56.191/pet?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sj2000617!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  #  swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 444
  ssl:
    key-store: classpath:lldt.ltd.jks
    key-store-password: ktp086j7b1bpd6g
    key-store-type: JKS

upload:
  location: /home/lldt/upload/
  avatarLocation: /home/lldt/avatar/
  url: https://lldt.ltd:444/upload/
  avatarUrl: https://lldt.ltd:444/avatar/

# 输出sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
