spring:
  datasource:
    url: jdbc:mysql://8.130.79.250/privacy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sj2000617!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 8.130.79.250
    port: 6379
    database: 0
    password: Sj2000617!
  #  swagger配置
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

server:
  port: 444
  ssl:
    key-store: classpath:jason21.top.jks
    key-store-password: 6dncpu83
    key-store-type: JKS

upload:
  location: /home/privacy/upload/
  avatarLocation: /home/privacy/avatar/
  chaincodeLocation: /home/PrivacyProtection/chaincode/src/
  url: https://jason21.top:444/upload/
  avatarUrl: https://jason21.top:444/avatar/
  chaincodeUrl: https://jason21.top:444/chaincode/

# 输出sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
