spring:
  datasource:
    url: jdbc:mysql://localhost/privacy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Sj2000617!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  #  swagger配置
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#server:
#  port: 444
#  ssl:
#    key-store: classpath:lldt.ltd.jks
#    key-store-password: lk13fmk4a68q9bd
#    key-store-type: JKS
#
#upload:
#  location: /Users/sade/IdeaProjects/upload/
#  avatarLocation: /Users/sade/IdeaProjects/avatar/
#  url: https://localhost:444/upload/
#  avatarUrl: https://localhost:444/avatar/
